/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auths/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auths/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auths/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auths/admin-only": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_adminOnly"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConcertController_findAll"];
        put?: never;
        post: operations["ConcertController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConcertController_findAllForAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/admin/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConcertController_getAdminSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ConcertController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/{id}/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ConcertController_reserve"];
        delete: operations["ConcertController_cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/admin/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReservationController_findAllHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reservations/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ReservationController_findMyHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example John Doe */
            fullName: string;
            /** @example john.doe@example.com */
            email: string;
            /** @example 123456 */
            password: string;
            /**
             * @example USER
             * @enum {string}
             */
            role?: "ADMIN" | "USER";
        };
        RegisterResponse: {
            /** @example Register success */
            message: string;
            /**
             * @example {
             *       "id": 1,
             *       "fullName": "John Doe",
             *       "email": "",
             *       "role": "USER",
             *       "createdAt": "2024-01-01T00:00:00.000Z"
             *     }
             */
            user: Record<string, never>;
        };
        LoginDto: {
            /** @example john.doe@example.com */
            email: string;
            /** @example 123456 */
            password: string;
        };
        UserDto: {
            /** @example 1 */
            id: number;
            /** @example John Doe */
            fullName: string;
            /** @example john.doe@example.com */
            email: string;
            /** @example user */
            role: string;
        };
        LoginResponse: {
            /** @example access_token_example */
            accessToken: string;
            /**
             * @example {
             *       "id": 1,
             *       "fullName": "John Doe",
             *       "email": "john.doe@example.com",
             *       "role": "USER"
             *     }
             */
            user: components["schemas"]["UserDto"];
        };
        GetConcertItem: {
            id: number;
            name: string;
            description: string;
            totalSeats: number;
            reservedSeats: number;
            availableSeats: number;
            isFull: boolean;
            isReservedByMe: boolean;
        };
        PaginationMetaDto: {
            total: number;
            totalPages: number;
            page: number;
            limit: number;
        };
        GetConcertResponse: {
            items: components["schemas"]["GetConcertItem"][];
            /** @example 100 */
            meta: components["schemas"]["PaginationMetaDto"];
        };
        CreateConcertDto: {
            /** @example Bangkok Music Night */
            name: string;
            /** @example Free concert ticket event */
            description: string;
            /** @example 100 */
            totalSeats: number;
        };
        CreateConcertResponse: {
            id: number;
            name: string;
            description: string;
            totalSeats: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GetConcertForAdminItem: {
            id: number;
            name: string;
            description: string;
            totalSeats: number;
            reservedSeats: number;
            availableSeats: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        GetConcertForAdminResponse: {
            items: components["schemas"]["GetConcertForAdminItem"][];
            /** @example 100 */
            meta: components["schemas"]["PaginationMetaDto"];
        };
        GetConcertAdminSummaryResponse: {
            totalSeats: number;
            reserved: number;
            cancelled: number;
        };
        DeleteConcertResponse: {
            message: string;
        };
        GetHistoryUserItem: {
            id: number;
            fullName: string;
            email: string;
            role: string;
        };
        GetHistoryConcertItem: {
            id: number;
            name: string;
            description: string;
            totalSeats: number;
        };
        GetAllHistoryItem: {
            id: number;
            status: string;
            action: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            user: components["schemas"]["GetHistoryUserItem"];
            concert: components["schemas"]["GetHistoryConcertItem"];
        };
        GetAllHistoryResponse: {
            items: components["schemas"]["GetAllHistoryItem"][];
            /** @example 100 */
            meta: components["schemas"]["PaginationMetaDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_adminOnly: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConcertController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConcertResponse"];
                };
            };
        };
    };
    ConcertController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConcertDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateConcertResponse"];
                };
            };
        };
    };
    ConcertController_findAllForAdmin: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConcertForAdminResponse"];
                };
            };
        };
    };
    ConcertController_getAdminSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetConcertAdminSummaryResponse"];
                };
            };
        };
    };
    ConcertController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteConcertResponse"];
                };
            };
        };
    };
    ConcertController_reserve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ConcertController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReservationController_findAllHistory: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetAllHistoryResponse"];
                };
            };
        };
    };
    ReservationController_findMyHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
